# Generated by Django 4.0.6 on 2022-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user1',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Staff_status'),
        ),
        migrations.AddField(
            model_name='user1',
            name='superuser',
            field=models.BooleanField(default=False, verbose_name='super_user_status'),
        ),
    ]
